#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Apr 07, 2020 05:35:18 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import help_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    help_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    help_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 13 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 11 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("647x197+418+190")
        top.minsize(120, 1)
        top.maxsize(1364, 749)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#f1e1d3")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.031, rely=0.0, height=61, width=604)
        self.Label1.configure(activebackground="#f1e1d3")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#f1e1d3")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#7c6249")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''This program allows you to crack a certain hash given the length of''')

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.031, rely=0.203, height=21, width=604)
        self.Label1_1.configure(activebackground="#f1e1d3")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#f1e1d3")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Label1_1.configure(foreground="#7c6249")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''what has been hashed''')

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.031, rely=0.406, height=21, width=604)
        self.Label1_2.configure(activebackground="#f1e1d3")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#f1e1d3")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font10)
        self.Label1_2.configure(foreground="#7c6249")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Supports:''')

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.031, rely=0.558, height=21, width=604)
        self.Label1_2.configure(activebackground="#f1e1d3")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#f1e1d3")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Label1_2.configure(foreground="#7c6249")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''MD5 and SHA256''')

        self.Label1_3 = tk.Label(top)
        self.Label1_3.place(relx=0.031, rely=0.66, height=21, width=604)
        self.Label1_3.configure(activebackground="#f1e1d3")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#f1e1d3")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Label1_3.configure(foreground="#7c6249")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Hashed strings with the length of up to 16''')

        self.Label1_4 = tk.Label(top)
        self.Label1_4.place(relx=0.031, rely=0.863, height=21, width=604)
        self.Label1_4.configure(activebackground="#f1e1d3")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#f1e1d3")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Label1_4.configure(foreground="#7c6249")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''The program uses bots to enhance the copmputing power - reducing time to solve''')

if __name__ == '__main__':
    vp_start_gui()





